#配置注册中心的端口
server:
  port: 8761
eureka:
  # 设置Eureka的hostname
  instance:
    hostname: EurekaServer
  # 设置不检索其他服务
  client:
    fetch-registry: false
  # 不注册自己
    register-with-eureka: false
  # 服务注册地址
    service-url:
      defaultZone: http://EurekaServer:${server.port}/eureka/