
server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置文件的所在仓库地址
          uri: https://github.com/triumphxx/config.git
          # 配置文件可查询目录
          search-paths: config-repo
          # git仓库的用户名
          username: triumphxx@163.com
          # git 仓库的密码
          password: wyphdx126321
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: triumphxx
      password: 123
      # 配置mq的连接信息
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



